const {onCall,HttpsError,onRequest}=require('firebase-functions/v2/https');
const {onSchedule}=require('firebase-functions/v2/scheduler');
const {defineSecret}=require('firebase-functions/params');
const admin=require('firebase-admin');
const crypto=require('crypto');
admin.initializeApp();
const db=admin.firestore();
const bucket=admin.storage().bucket();
const PAYMOB_API_KEY=defineSecret('PAYMOB_API_KEY');
const PAYMOB_HMAC_SECRET=defineSecret('PAYMOB_HMAC_SECRET');
const AI_API_KEY=defineSecret('AI_API_KEY');

function requireAuth(req){if(!req.auth)throw new HttpsError('unauthenticated','يجب تسجيل الدخول.');return req.auth;}
function requireRole(req,roles){const a=requireAuth(req);if(!roles.includes(a.token.role))throw new HttpsError('permission-denied','غير مصرح.');return a;}
async function user(uid){const s=await db.doc(`users/${uid}`).get();if(!s.exists)throw new HttpsError('not-found','المستخدم غير موجود.');return s.data();}
async function activeSubscription(uid){const s=await db.collection('subscriptions').where('studentId','==',uid).where('status','==','ACTIVE').limit(5).get();const now=Date.now();for(const d of s.docs){const x=d.data();if(x.type==='lifetime')return x;if(x.endAt?.toMillis()>now)return x;}return null;}
function addCalendarMonthsClamped(date, months){
  const d=new Date(date), day=d.getDate();
  const target=new Date(d.getFullYear(),d.getMonth()+months,1,d.getHours(),d.getMinutes(),d.getSeconds(),d.getMilliseconds());
  const last=new Date(target.getFullYear(),target.getMonth()+1,0).getDate();
  target.setDate(Math.min(day,last));
  return target;
}
function subscriptionEnd(start,type){
  if(type==='lifetime')return null;
  const next=type==='monthly'?addCalendarMonthsClamped(start,1):addCalendarMonthsClamped(start,12);
  next.setDate(next.getDate()-1);
  return next;
}

async function canAccessLesson(uid,lessonId){const [ls,sub]=await Promise.all([db.doc(`lessons/${lessonId}`).get(),activeSubscription(uid)]);if(!ls.exists)throw new HttpsError('not-found','الدرس غير موجود.');const l=ls.data();const p=await user(uid);if(!sub)throw new HttpsError('permission-denied','الاشتراك غير نشط.');if(l.gradeId && l.gradeId!==p.gradeId)throw new HttpsError('permission-denied','الصف غير مطابق.');
  const gate=l.prerequisiteExamId;if(gate){const passed=await db.collection('examAttempts').where('studentId','==',uid).where('examId','==',gate).where('passed','==',true).limit(1).get();if(passed.empty)throw new HttpsError('permission-denied','يجب اجتياز الاختبار السابق.');}
  return {lesson:l,subscription:sub};}

exports.completeStudentRegistration=onCall(async(req)=>{const a=requireAuth(req);const {name,gradeId}=req.data||{};if(!name||!gradeId)throw new HttpsError('invalid-argument','الاسم والصف مطلوبان.');const g=await db.doc(`grades/${gradeId}`).get();if(!g.exists||g.data().active===false)throw new HttpsError('failed-precondition','الصف غير متاح.');await db.doc(`users/${a.uid}`).set({name, email:a.token.email||null, role:'student',gradeId,status:'active',createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});return {ok:true};});

exports.updateStudentProfile=onCall(async(req)=>{const a=requireAuth(req);const {name,photoURL}=req.data||{};if(!name||name.length<2)throw new HttpsError('invalid-argument','الاسم غير صالح.');await db.doc(`users/${a.uid}`).update({name,photoURL:photoURL||'',updatedAt:admin.firestore.FieldValue.serverTimestamp()});return {ok:true};});

exports.getLessonAccess=onCall(async(req)=>{const a=requireAuth(req);const {lessonId}=req.data||{};const {lesson}=await canAccessLesson(a.uid,lessonId);const unit=(await db.doc(`units/${lesson.unitId}`).get()).data()||{};const subject=(await db.doc(`subjects/${unit.subjectId}`).get()).data()||{};let video=null;if(lesson.videoId){const vd=await db.doc(`videos/${lesson.videoId}`).get();if(vd.exists){const v=vd.data();if(v.storagePath){const file=bucket.file(v.storagePath);const [url]=await file.getSignedUrl({version:'v4',action:'read',expires:Date.now()+5*60*1000,responseDisposition:'inline',responseType:v.contentType||'video/mp4'});video={url,expiresIn:300};}}}return {allowed:true,title:lesson.title,summary:lesson.summary||'',subjectName:subject.name||'',video,nextLesson:null};});

exports.getVideoAccess=onCall(async(req)=>{const a=requireAuth(req);const {videoId,lessonId}=req.data||{};if(!videoId||!lessonId)throw new HttpsError('invalid-argument','بيانات ناقصة.');await canAccessLesson(a.uid,lessonId);const v=await db.doc(`videos/${videoId}`).get();if(!v.exists)throw new HttpsError('not-found','الفيديو غير موجود.');const x=v.data();const [url]=await bucket.file(x.storagePath).getSignedUrl({version:'v4',action:'read',expires:Date.now()+5*60*1000,responseDisposition:'inline',responseType:x.contentType||'video/mp4'});return {url,expiresIn:300};});

exports.saveVideoProgress=onCall(async(req)=>{const a=requireAuth(req);const {lessonId,lastPosition,watchedPercent}=req.data||{};await canAccessLesson(a.uid,lessonId);await db.doc(`progress/${a.uid}_${lessonId}`).set({studentId:a.uid,lessonId,lastPosition:Number(lastPosition)||0,watchedPercent:Math.min(100,Math.max(0,Number(watchedPercent)||0)),updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});return {ok:true};});

exports.createExam=onCall(async(req)=>{
  const a=requireRole(req,['teacher','admin']);
  const {title,type,passScore,gradingMode,instructions,questions,subjectId,gradeId}=req.data||{};
  if(!title||!Array.isArray(questions)||!questions.length||!subjectId||!gradeId)throw new HttpsError('invalid-argument','بيانات الاختبار ناقصة.');
  if(a.token.role==='teacher'){
    const link=await db.collection('teacherSubjects').where('teacherId','==',a.uid).where('subjectId','==',subjectId).limit(1).get();
    if(link.empty)throw new HttpsError('permission-denied','لا تملك صلاحية هذه المادة.');
  }
  const examRef=db.collection('exams').doc();
  const cleanQuestions=questions.map((q,i)=>({id:q.id||crypto.randomUUID(),text:String(q.text||''),type:q.type||'mcq',options:Array.isArray(q.options)?q.options:[],points:Number(q.points||1)}));
  const key={}; questions.forEach((q,i)=>{if(q.correctAnswer!==undefined)key[cleanQuestions[i].id]=q.correctAnswer});
  await examRef.set({title,type,passScore:Number(passScore),gradingMode:gradingMode||'auto',instructions:instructions||'',questions:cleanQuestions,subjectId,gradeId,status:'PUBLISHED',createdBy:a.uid,createdAt:admin.firestore.FieldValue.serverTimestamp()});
  await db.doc(`examAnswerKeys/${examRef.id}`).set(key);
  return {id:examRef.id};
});

exports.startOrResumeExam=onCall(async(req)=>{const a=requireAuth(req);const {examId,lessonId}=req.data||{};let eid=examId;if(!eid&&lessonId){const l=await db.doc(`lessons/${lessonId}`).get();eid=l.data()?.examId;if(!eid)throw new HttpsError('failed-precondition','لا يوجد اختبار مرتبط.');}const e=await db.doc(`exams/${eid}`).get();if(!e.exists)throw new HttpsError('not-found','الاختبار غير موجود.');const ex=e.data();const sub=await activeSubscription(a.uid);if(!sub)throw new HttpsError('permission-denied','الاشتراك غير نشط.');const existing=await db.collection('examAttempts').where('studentId','==',a.uid).where('examId','==',eid).where('status','==','IN_PROGRESS').limit(1).get();if(!existing.empty)return {attempt:{id:existing.docs[0].id,...existing.docs[0].data()},exam:sanitizeExam(ex)};const attempts=await db.collection('examAttempts').where('studentId','==',a.uid).where('examId','==',eid).get();if(attempts.docs.some(d=>['SUBMITTED','PASSED'].includes(d.data().status)))throw new HttpsError('failed-precondition','تم استخدام المحاولة.');const ref=db.collection('examAttempts').doc();const data={studentId:a.uid,examId:eid,lessonId:lessonId||null,startTime:admin.firestore.FieldValue.serverTimestamp(),status:'IN_PROGRESS',answers:{},score:null,passed:null,createdAt:admin.firestore.FieldValue.serverTimestamp()};await ref.set(data);return {attempt:{id:ref.id,...data},exam:sanitizeExam(ex)};});
function sanitizeExam(ex){return {...ex,questions:(ex.questions||[]).map(q=>({id:q.id,text:q.text,type:q.type,options:q.options||[],points:q.points||1}))};}

exports.submitExamAttempt=onCall(async(req)=>{const a=requireAuth(req);const {attemptId,answers}=req.data||{};const ref=db.doc(`examAttempts/${attemptId}`);const s=await ref.get();if(!s.exists||s.data().studentId!==a.uid)throw new HttpsError('permission-denied','المحاولة غير متاحة.');const at=s.data();if(at.status!=='IN_PROGRESS')throw new HttpsError('failed-precondition','المحاولة ليست مفتوحة.');const ex=(await db.doc(`exams/${at.examId}`).get()).data();const questions=ex.questions||[];let auto=0,max=0,needsManual=false;for(const q of questions){max+=Number(q.points||1);if(q.type==='mcq'||q.type==='truefalse'){if(String(answers?.[q.id]??'')===String(key[q.id]??''))auto+=Number(q.points||1)}else needsManual=true;}const mode=ex.gradingMode==='manual'||needsManual?'MANUAL_REVIEW':'AUTO';const score=mode==='AUTO'?auto:null;const passed=mode==='AUTO'?score>=Number(ex.passScore):null;await ref.update({answers:answers||{},submittedAt:admin.firestore.FieldValue.serverTimestamp(),status:mode==='AUTO'?'SUBMITTED':'AWAITING_GRADING',score,passed,maxScore:max,gradingMode:mode});return {ok:true,message:mode==='AUTO'?(passed?'تم النجاح.':'تم التسليم والنتيجة لم تحقق شرط النجاح.'):'تم التسليم، في انتظار تصحيح المدرس.'};});

exports.requestRetake=onCall(async(req)=>{const a=requireAuth(req);const {attemptId}=req.data||{};const s=await db.doc(`examAttempts/${attemptId}`).get();if(!s.exists||s.data().studentId!==a.uid||s.data().passed!==false)throw new HttpsError('permission-denied','غير مسموح بطلب إعادة.');const r=await db.collection('retakeRequests').add({studentId:a.uid,attemptId,examId:s.data().examId,status:'PENDING',createdAt:admin.firestore.FieldValue.serverTimestamp()});return {id:r.id};});

exports.teacherSubjectsList=onCall(async(req)=>{
  const a=requireRole(req,['teacher','admin']);
  if(a.token.role==='admin'){
    const s=await db.collection('subjects').limit(100).get(); return {items:s.docs.map(d=>({id:d.id,...d.data()}))};
  }
  const links=await db.collection('teacherSubjects').where('teacherId','==',a.uid).limit(100).get();
  const items=[]; for(const l of links.docs){const id=l.data().subjectId;const s=await db.doc(`subjects/${id}`).get();if(s.exists)items.push({id:s.id,...s.data()});}
  return {items};
});

exports.teacherDashboard=onCall(async(req)=>{const a=requireRole(req,['teacher','admin']);if(a.token.role==='admin')return {subjects:await count('subjects'),students:await count('users','student'),pendingGrading:await count('examAttempts','AWAITING_GRADING','status'),pendingRetakes:await count('retakeRequests','PENDING','status')};const ts=await db.collection('teacherSubjects').where('teacherId','==',a.uid).get();const ids=ts.docs.map(d=>d.data().subjectId);return {subjects:ids.length,students:0,pendingGrading:0,pendingRetakes:0};});
async function count(col,value,field='role'){let q=db.collection(col);if(value!==undefined)q=q.where(field,'==',value);const s=await q.count().get();return s.data().count;}
exports.teacherPendingGrading=onCall(async(req)=>{const a=requireRole(req,['teacher','admin']);const s=await db.collection('examAttempts').where('status','==','AWAITING_GRADING').limit(100).get();return {items:await Promise.all(s.docs.map(async d=>{const x=d.data();const [e,u]=await Promise.all([db.doc(`exams/${x.examId}`).get(),db.doc(`users/${x.studentId}`).get()]);return {id:d.id,status:x.status,examTitle:e.data()?.title||'',studentName:u.data()?.name||''};}))};});
exports.getGradingAttempt=onCall(async(req)=>{const actor=requireRole(req,['teacher','admin']);const {attemptId}=req.data||{};const a=await db.doc(`examAttempts/${attemptId}`).get();if(!a.exists)throw new HttpsError('not-found','المحاولة غير موجودة.');const x=a.data(),e=(await db.doc(`exams/${x.examId}`).get()).data(),u=(await db.doc(`users/${x.studentId}`).get()).data(); if(actor.token.role==='teacher'){const link=await db.collection('teacherSubjects').where('teacherId','==',actor.uid).where('subjectId','==',e.subjectId).limit(1).get();if(link.empty)throw new HttpsError('permission-denied','لا تملك صلاحية هذه المادة.');} return {examTitle:e.title,studentName:u.name,questions:(e.questions||[]).map(q=>({id:q.id,text:q.text,points:q.points||1,answer:x.answers?.[q.id]||'',awarded:0,comment:''}))};});
exports.gradeAttempt=onCall(async(req)=>{const a=requireRole(req,['teacher','admin']);const {attemptId,scores,comments}=req.data||{};const ref=db.doc(`examAttempts/${attemptId}`);const s=await ref.get();if(!s.exists)throw new HttpsError('not-found','المحاولة غير موجودة.');const e=(await db.doc(`exams/${s.data().examId}`).get()).data();if(a.token.role==='teacher'){const link=await db.collection('teacherSubjects').where('teacherId','==',a.uid).where('subjectId','==',e.subjectId).limit(1).get();if(link.empty)throw new HttpsError('permission-denied','لا تملك صلاحية هذه المادة.');}const total=(e.questions||[]).reduce((n,q)=>n+Number(q.points||1),0);const score=(scores||[]).reduce((n,v)=>n+Number(v||0),0);const passed=score>=Number(e.passScore);await ref.update({score,maxScore:total,passed,status:'REVIEWED',reviewedBy:a.uid,reviewedAt:admin.firestore.FieldValue.serverTimestamp(),reviewComments:comments||[]});await db.collection('notifications').add({userId:s.data().studentId,title:'تم تصحيح امتحانك',body:`تم اعتماد نتيجة ${e.title}.`,read:false,createdAt:admin.firestore.FieldValue.serverTimestamp()});return {ok:true};});
exports.adminDashboard=onCall(async(req)=>{requireRole(req,['admin']);return {students:await count('users','student'),teachers:await count('users','teacher'),subjects:await count('subjects'),lessons:await count('lessons'),exams:await count('exams'),activeSubscriptions:await count('subscriptions','ACTIVE','status'),expiredSubscriptions:await count('subscriptions','EXPIRED','status'),revenue:0,pendingPayments:await count('payments','PENDING','status'),certificates:await count('certificates'),retakeRequests:await count('retakeRequests','PENDING','status')}});
exports.adminCreate=onCall(async(req)=>{requireRole(req,['admin']);const {collection:col,data}=req.data||{};const allowed=['grades','subjects','units','lessons','exams','coupons','certificates'];if(!allowed.includes(col))throw new HttpsError('permission-denied','المجموعة غير مسموحة.');const r=await db.collection(col).add({...data,createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()});return {id:r.id};});
exports.adminDelete=onCall(async(req)=>{requireRole(req,['admin']);const {collection:col,id}=req.data||{};const allowed=['grades','subjects','units','lessons','exams','coupons','certificates'];if(!allowed.includes(col))throw new HttpsError('permission-denied','المجموعة غير مسموحة.');await db.doc(`${col}/${id}`).delete();return {ok:true};});
exports.updatePublicSettings=onCall(async(req)=>{requireRole(req,['admin']);const {vodafone,instapay,paymobPublic,appCheckKey}=req.data||{};await db.doc('settings/public').set({vodafone,instapay,paymobPublic,appCheckKey,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});return {ok:true};});
exports.markNotificationsRead=onCall(async(req)=>{const a=requireAuth(req);const s=await db.collection('notifications').where('userId','==',a.uid).where('read','==',false).limit(500).get();const b=db.batch();s.docs.forEach(d=>b.update(d.ref,{read:true}));await b.commit();return {count:s.size};});

exports.submitManualPayment=onCall(async(req)=>{const a=requireAuth(req);const {planId,method,receiptUrl,storagePath,couponCode}=req.data||{};const p=await db.doc(`plans/${planId}`).get();if(!p.exists)throw new HttpsError('not-found','الخطة غير موجودة.');const plan=p.data(),student=await user(a.uid);if(plan.gradeId!==student.gradeId)throw new HttpsError('permission-denied','الخطة لا تناسب الصف.');let amount=Number(plan.price);if(couponCode)amount=await applyCoupon(couponCode,a.uid,amount,plan);const pay=await db.collection('payments').add({studentId:a.uid,planId,method,amount,receiptUrl,storagePath,status:'PENDING',aiConfidence:null,createdAt:admin.firestore.FieldValue.serverTimestamp()});await db.collection('paymentReviews').doc(pay.id).set({paymentId:pay.id,status:'PENDING',createdAt:admin.firestore.FieldValue.serverTimestamp()});return {paymentId:pay.id};});
async function applyCoupon(code,uid,amount,plan){const s=await db.collection('coupons').where('code','==',code).limit(1).get();if(s.empty)throw new HttpsError('invalid-argument','كود الخصم غير صالح.');const c=s.docs[0].data(),now=Date.now();if(c.startAt?.toMillis()>now||c.endAt?.toMillis()<now)throw new HttpsError('failed-precondition','الكوبون منتهي أو غير فعال.');const uses=await db.collection('couponUses').where('couponId','==',s.docs[0].id).where('studentId','==',uid).get();if(uses.size>=Number(c.maxUsesPerStudent||1))throw new HttpsError('failed-precondition','تم استخدام الكوبون الحد الأقصى.');const discount=c.discountType==='percent'?amount*(Number(c.discountValue)/100):Number(c.discountValue);return Math.max(0,amount-discount);}

exports.reviewPayment=onCall(async(req)=>{const a=requireRole(req,['admin']);const {paymentId,action}=req.data||{};const ref=db.doc(`payments/${paymentId}`);const s=await ref.get();if(!s.exists)throw new HttpsError('not-found','الدفع غير موجود.');if(action==='reject'){await ref.update({status:'REJECTED',reviewedBy:a.uid,reviewedAt:admin.firestore.FieldValue.serverTimestamp()});return {ok:true};}if(action!=='approve')throw new HttpsError('invalid-argument','إجراء غير صالح.');await activateSubscriptionFromPayment(ref,s.data(),a.uid);return {ok:true};});
async function activateSubscriptionFromPayment(payRef,pay,actor){const plan=(await db.doc(`plans/${pay.planId}`).get()).data();const start=new Date();let end=null,type=plan.type==='lifetime'?'lifetime':plan.type;if(type!=='lifetime')end=subscriptionEnd(start,type);const sub=await db.collection('subscriptions').add({studentId:pay.studentId,planId:pay.planId,plan:type,type,status:'ACTIVE',startAt:admin.firestore.Timestamp.fromDate(start),endAt:end?admin.firestore.Timestamp.fromDate(end):null,sourcePaymentId:payRef.id,activatedBy:actor,createdAt:admin.firestore.FieldValue.serverTimestamp()});await payRef.update({status:'APPROVED',subscriptionId:sub.id,reviewedBy:actor,reviewedAt:admin.firestore.FieldValue.serverTimestamp()});await db.collection('notifications').add({userId:pay.studentId,title:'تم تفعيل اشتراكك',body:'أصبح محتوى صفك متاحًا حسب الخطة.',read:false,createdAt:admin.firestore.FieldValue.serverTimestamp()});}

exports.createCardCheckout=onCall({secrets:[PAYMOB_API_KEY]},async(req)=>{requireAuth(req);const {planId}=req.data||{};const p=await db.doc(`plans/${planId}`).get();if(!p.exists)throw new HttpsError('not-found','الخطة غير موجودة.');if(!PAYMOB_API_KEY.value())throw new HttpsError('failed-precondition','بوابة الدفع غير مهيأة بعد.');/* Integrate Paymob Hosted Checkout here using account-specific integration IDs. */return {checkoutUrl:null,provider:'paymob'};});

exports.paymobWebhook=onRequest({secrets:[PAYMOB_HMAC_SECRET]},async(req,res)=>{try{const secret=PAYMOB_HMAC_SECRET.value();if(!secret)return res.status(503).send('not configured');const h=req.headers['hmac'];const raw=req.rawBody||Buffer.from(JSON.stringify(req.body));const calc=crypto.createHmac('sha512',secret).update(raw).digest('hex');if(h&&h!==calc)return res.status(401).send('invalid hmac');/* Verify transaction status + amount + order against provider API, then activate subscription. */return res.status(200).send('ok')}catch(e){console.error(e);return res.status(500).send('error')}});

exports.verifyReceiptAI=onCall({secrets:[AI_API_KEY]},async(req)=>{requireRole(req,['admin']);const {paymentId}=req.data||{};if(!AI_API_KEY.value())return {status:'MANUAL_REVIEW',confidence:0,reason:'AI secret not configured'};/* Provider adapter intentionally isolated. Never auto-approve on weak confidence. */return {status:'MANUAL_REVIEW',confidence:0,reason:'Configure your chosen receipt OCR/vision provider.'};});

exports.issueCertificate=onCall(async(req)=>{const a=requireRole(req,['teacher','admin']);const {studentId,attemptId,minScore}=req.data||{};const s=await db.doc(`examAttempts/${attemptId}`).get();if(!s.exists||s.data().studentId!==studentId||s.data().passed!==true||Number(s.data().score)<Number(minScore))throw new HttpsError('failed-precondition','شروط الشهادة غير مستوفاة.');const u=(await db.doc(`users/${studentId}`).get()).data();const e=(await db.doc(`exams/${s.data().examId}`).get()).data();const num='OF-'+new Date().getFullYear()+'-'+crypto.randomBytes(5).toString('hex').toUpperCase();const r=await db.collection('certificates').add({studentId,studentName:u.name,title:e.title,score:s.data().score,certificateNumber:num,issuedBy:a.uid,issuedAt:admin.firestore.FieldValue.serverTimestamp()});return {id:r.id,certificateNumber:num};});

exports.expireSubscriptions=onSchedule('every 60 minutes',async()=>{const now=admin.firestore.Timestamp.now();const s=await db.collection('subscriptions').where('status','==','ACTIVE').where('endAt','<=',now).limit(500).get();const b=db.batch();s.docs.forEach(d=>{if(d.data().type!=='lifetime')b.update(d.ref,{status:'EXPIRED',expiredAt:admin.firestore.FieldValue.serverTimestamp()})});await b.commit();});
